package com.acmeplex.model;
import jakarta.persistence.*;
import java.time.LocalDate;

@Entity
public class Credit {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) 
    private int creditID;

    private String type; 
    private Double amount; 
    private String redeemCode; 
    private LocalDate dateCreated; 
    private LocalDate expiryDate; 

    // RECEIVES: Many credits can be received to one user
    @ManyToOne 
    @JoinColumn(name = "userID") 
    private User user;

    // GENERATES: One credit is generated by one ticket
    @OneToOne
    @JoinColumn(name = "ticketID")
    private Ticket ticket;

    // Constructors
    public Credit() {}
    
    public Credit(String type, Double amount, String redeemCode, LocalDate dateCreated, LocalDate expiryDate) {
        this.type = type;
        this.amount = amount;
        this.redeemCode = redeemCode;
        this.dateCreated = dateCreated;
        this.expiryDate = expiryDate;
    }

    // Getters

    public int getCreditID() {
        return creditID;
    }  

    public String getType() {
        return type;
    }

    public Double getAmount() {
        return amount;
    }

    public String getRedeemCode() {
        return redeemCode;
    }

    public LocalDate getDateCreated() {
        return dateCreated;
    }

    public LocalDate getExpiryDate() {
        return expiryDate;
    }

    public User getUser() {
        return user;
    }
    
    public Ticket getTicket() {
        return ticket;
    }

    // Setters

    public void setCreditID(int creditID) {
        this.creditID = creditID;
    }
    

    public void setType(String type) {
        this.type = type;
    }

    public void setAmount(Double amount) {
        this.amount = amount;
    }

    public void setRedeemCode(String redeemCode) {
        this.redeemCode = redeemCode;
    }

    public void setDateCreated(LocalDate dateCreated) {
        this.dateCreated = dateCreated;
    }

    public void setExpiryDate(LocalDate expiryDate) {
        this.expiryDate = expiryDate;
    }    

    public void setUser(User user) {
        this.user = user;
    }

    public void setTicket(Ticket ticket) {
        this.ticket = ticket;
    }
}
